name: GH-Pages Build and Main Deploy

on:
  workflow_call:

jobs:
  build:
    name: Build and Main Deploy
    concurrency:
      group: gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4

      - name: Install coverage dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r .github/scripts/requirements-coverage.txt
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Print metadata
        run: |
          run_information="Repository: ${{ github.repository }} Commit SHA:${{ github.sha }} Workflow: ${{ github.workflow }} Run:${{ github.run_id }}"
          echo $run_information

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: coverage_report
          path: ./coverage_dashboard

      - name: Download docs
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: ./docs_rendered

      - name: Download verification reports
        uses: actions/download-artifact@v3
        with:
          name: verification_dashboard
          path: ./verification_dashboard

      - name: Download RISCOF report
        uses: actions/download-artifact@v3
        with:
          name: riscof-report
          path: ./riscof_dashboard

      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ./public.checkout

      - name: Preserve only valid items
        run: |
          mkdir -p ./public.old
          mv ./public.checkout/doctrees ./public.old/ | true
          mv ./public.checkout/html ./public.old/ | true

      - name: Update webpage
        if: github.event_name != 'pull_request'
        run: |
          mv coverage_dashboard/*.zip .
          sis -d webpage \
            --include-documentation \
            --doc-project-name "Cores VeeR EL2" \
            --loc-github-ref-name ${{ github.ref_name }} \
            --loc-github-event-name ${{ github.event_name }} \
            --pr-number 0
          # use docs from the artifact
          rm -rf public.new/html/main/docs_rendered
          mkdir -p public.new/html/main/docs_rendered
          mv ./docs_rendered/* public.new/html/main/docs_rendered
          mv data_*_verilator_info.zip public.new/html/main/
          mv data.zip public.new/html/main/
          mv data_v.zip public.new/html/main/
          mv data_both.zip public.new/html/main/
          echo ${GITHUB_RUN_ID} > public.new/html/main/run_id
          tar -acf webpage.tar.gz public.new

      - name: Update webpage PR
        if: github.event_name == 'pull_request'
        run: |
          mv coverage_dashboard/*.zip .
          sis -d webpage \
            --include-documentation \
            --doc-project-name "Cores VeeR EL2" \
            --loc-github-ref-name ${{ github.ref_name }} \
            --loc-github-event-name ${{ github.event_name }} \
            --pr-number ${{ github.event.number }}
          # use docs from the artifact
          rm -rf public.new/html/dev/${{ github.event.number }}/docs_rendered
          mkdir -p public.new/html/dev/${{ github.event.number }}/docs_rendered
          mv ./docs_rendered/* public.new/html/dev/${{ github.event.number }}/docs_rendered
          mv data_*_verilator_info.zip public.new/html/dev/${{ github.event.number }}/
          mv data.zip public.new/html/dev/${{ github.event.number }}/
          mv data_v.zip public.new/html/dev/${{ github.event.number }}/
          mv data_both.zip public.new/html/dev/${{ github.event.number }}/
          echo ${GITHUB_RUN_ID} > public.new/html/dev/${{ github.event.number }}/run_id
          tar -acf webpage.tar.gz public.new

      - name: Add redirect index page
        run: |
          cp .github/scripts/indexgen/index_redirect/index.html ./public.new/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public.new

      - name: Save PR number
        if: github.event_name == 'pull_request'
        run: |
          echo "number=${{ github.event.number }}" >> pr_number.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: github.event_name == 'pull_request'
        with:
          name: pr_number
          path: ./pr_number.txt

      - name: Pack webpage as an artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: webpage
          path: ./webpage.tar.gz
