name: RISCOF tests

on:
  workflow_call:

jobs:

  tests:
    name: Run RISCOF tests
    runs-on: ubuntu-24.04
    container: ghcr.io/antmicro/cores-veer-el2:20250123123840
    strategy:
      fail-fast: false
      matrix:
        coverage: ["branch", "toggle"] #TODO: add functional coverage
        priv: ["", "u"]
    env:
      DEBIAN_FRONTEND: "noninteractive"
      CCACHE_DIR: "/opt/riscof/.cache/"

    steps:
      - name: Install utils
        run: |
          sudo apt -qqy update && sudo apt -qqy --no-install-recommends install \
            git ccache python3-minimal python3-pip device-tree-compiler \
            gcc-riscv64-unknown-elf build-essential ninja-build

      - name: Setup repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install coverage dependencies
        shell: bash
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r .github/scripts/requirements-coverage.txt
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Install RISCOF
        run: |
          pip3 install git+https://github.com/riscv/riscof@a25e315

      - name: Clone tests
        shell: bash
        run: |
          mkdir -p riscof
          pushd riscof
            riscof --verbose info arch-test --clone
            # FIXME: It seems impossible to turn off Zicsr extension. A
            # temporary solution is to remove the tests.
            rm -rf riscv-arch-test/riscv-test-suite/rv32i_m/privilege/
          popd

      - name: Configure RISCOF
        shell: bash
        run: |
          pushd riscof
            # Copy RISCOF configuration
            cp ../tools/riscof/config.ini ./
            cp -r ../tools/riscof/spike ./
            cp -r ../tools/riscof/veer ./
            # Build the test list
            riscof testlist --config=config.ini --suite=riscv-arch-test/riscv-test-suite/ --env=riscv-arch-test/riscv-test-suite/env
          popd

      - name: Build VeeR model
        shell: bash
        run: |
          export PATH=/opt/verilator/bin:$PATH
          export RV_ROOT=`pwd`
          pushd riscof
            $RV_ROOT/configs/veer.config
            VEER_OPTS=""
            if  [[ "${{ matrix.priv }}" == *"u"* ]]; then
              VEER_OPTS="-set=user_mode=1 -set=smepmp=1"
            fi
            make -f $RV_ROOT/tools/Makefile verilator-build CONF_PARAMS="-set build_axi4 $VEER_OPTS" COVERAGE=${{ matrix.coverage }}
          popd

      - name: Run tests, collect coverage
        shell: bash
        run: |
          export PATH=/opt/verilator/bin:/opt/spike/bin:$PATH
          pushd riscof
            riscof run --no-browser --config=config.ini --suite=riscv-arch-test/riscv-test-suite/ --env=riscv-arch-test/riscv-test-suite/env
            mkdir -p coverage
            verilator_coverage -write ./coverage/coverage.dat `find ./riscof_work/ -type f -name "coverage.dat"`
          popd

      - name: Prepare coverage data
        shell: bash
        run: |
          export PATH=/opt/verilator/bin:$PATH
          sis -d convert --dat-dir riscof/coverage/
          mv riscof/coverage/coverage.info \
             riscof/coverage/coverage_riscof_${{matrix.priv}}_${{ matrix.coverage }}.info

      - name: Prepare report
        shell: bash
        run: |
          PYTEST_STYLE_SRC_DIR=$(pwd)/.github/scripts/pytest/
          PYTEST_CSS=${PYTEST_STYLE_SRC_DIR}/css/styles.css
          pushd riscof/riscof_work
            bash ${PYTEST_STYLE_SRC_DIR}/style_pytest_report.sh ${PYTEST_STYLE_SRC_DIR} . report.html
            echo "/* Custom CSS */" >>style.css
            cat ${PYTEST_CSS} >>style.css
          popd

      - name: Pack artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: riscof_coverage_data_${{matrix.priv}}_${{ matrix.coverage }}
          path: riscof/coverage/*.info

      - name: Pack artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: riscof-report_${{matrix.priv}}_${{ matrix.coverage }}
          path: |
            riscof/riscof_work/report.html
            riscof/riscof_work/style.css
            riscof/riscof_work/assets
            riscof/riscof_work/script
