name: VeeR-EL2 verification

on:
  workflow_call:

jobs:
  tests:
    name: UVM tests
    runs-on: ubuntu-latest
    container: ghcr.io/antmicro/cores-veer-el2:20250103160559
    env:
      CCACHE_DIR: "/opt/uvm/.cache/"
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install prerequisities
        run: |
          sudo apt -qqy update && sudo apt -qqy --no-install-recommends install \
            git build-essential ccache

      - name: Setup environment
        run: |
          echo "/opt/verilator_uvm/bin" >> $GITHUB_PATH
          RV_ROOT=`pwd`
          echo "RV_ROOT=$RV_ROOT" >> $GITHUB_ENV
          PYTHONUNBUFFERED=1
          echo "PYTHONUNBUFFERED=$PYTHONUNBUFFERED" >> $GITHUB_ENV

      - name: Build UVM testbench
        run: |
          make -C testbench/uvm/mem build -j$(nproc)

      - name: Run UVM testbench
        run: |
          make -C testbench/uvm/mem simulate | tee test.out

      - name: Upload test output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: uvm_test_output
          path: test.out
