name: Renode tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    container: ghcr.io/antmicro/cores-veer-el2:20250103160559
    strategy:
      fail-fast: false
    env:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt -qqy update && sudo apt -qqy --no-install-recommends install \
            git python3 python3-pip build-essential ninja-build ccache \
            gcc-riscv64-unknown-elf
          pip3 install meson

      - name: Build tests
        run: |
          export RV_ROOT=`pwd`
          cd ./tools/renode
          ./build-all-tests.sh

      - name: Run tests
        run: |
          cd ./tools/renode
          pip install -r /opt/renode/tests/requirements.txt
          /opt/renode/renode-test veer.robot

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: renode_results
          path: tools/renode/logs/*log
